export const arrNationDefault = [
  { checked: false, label: 'Afghanistan', value: 'AF' },
  { checked: false, label: 'Åland Islands', value: 'AX' },
  { checked: false, label: 'Albania', value: 'AL' },
  { checked: false, label: 'Algeria', value: 'DZ' },
  { checked: false, label: 'American Samoa', value: 'AS' },
  { checked: false, label: 'Andorra', value: 'AD' },
  { checked: false, label: 'Angola', value: 'AO' },
  { checked: false, label: 'Anguilla', value: 'AI' },
  { checked: false, label: 'Antarctica', value: 'AQ' },
  { checked: false, label: 'Antigua &amp; Barbuda', value: 'AG' },
  { checked: false, label: 'Argentina', value: 'AR' },
  { checked: false, label: 'Armenia', value: 'AM' },
  { checked: false, label: 'Aruba', value: 'AW' },
  { checked: false, label: 'Australia', value: 'AU' },
  { checked: false, label: 'Austria', value: 'AT' },
  { checked: false, label: 'Azerbaijan', value: 'AZ' },
  { checked: false, label: 'Bahamas', value: 'BS' },
  { checked: false, label: 'Bahrain', value: 'BH' },
  { checked: false, label: 'Bangladesh', value: 'BD' },
  { checked: false, label: 'Barbados', value: 'BB' },
  { checked: false, label: 'Belarus', value: 'BY' },
  { checked: false, label: 'Belgium', value: 'BE' },
  { checked: false, label: 'Belize', value: 'BZ' },
  { checked: false, label: 'Benin', value: 'BJ' },
  { checked: false, label: 'Bermuda', value: 'BM' },
  { checked: false, label: 'Bhutan', value: 'BT' },
  { checked: false, label: 'Bolivia', value: 'BO' },
  { checked: false, label: 'Bosnia &amp; Herzegovina', value: 'BA' },
  { checked: false, label: 'Botswana', value: 'BW' },
  { checked: false, label: 'Bouvet Island', value: 'BV' },
  { checked: false, label: 'Brazil', value: 'BR' },
  { checked: false, label: 'British Indian Ocean Territory', value: 'IO' },
  { checked: false, label: 'British Virgin Islands', value: 'VG' },
  { checked: false, label: 'Brunei', value: 'BN' },
  { checked: false, label: 'Bulgaria', value: 'BG' },
  { checked: false, label: 'Burkina Faso', value: 'BF' },
  { checked: false, label: 'Burundi', value: 'BI' },
  { checked: false, label: 'Cambodia', value: 'KH' },
  { checked: false, label: 'Cameroon', value: 'CM' },
  { checked: false, label: 'Canada', value: 'CA' },
  { checked: false, label: 'Cape Verde', value: 'CV' },
  { checked: false, label: 'Caribbean Netherlands', value: 'BQ' },
  { checked: false, label: 'Cayman Islands', value: 'KY' },
  { checked: false, label: 'Central African Republic', value: 'CF' },
  { checked: false, label: 'Chad', value: 'TD' },
  { checked: false, label: 'Chile', value: 'CL' },
  { checked: false, label: 'China', value: 'CN' },
  { checked: false, label: 'Christmas Island', value: 'CX' },
  { checked: false, label: 'Cocos (Keeling) Islands', value: 'CC' },
  { checked: false, label: 'Colombia', value: 'CO' },
  { checked: false, label: 'Comoros', value: 'KM' },
  { checked: false, label: 'Congo - Brazzaville', value: 'CG' },
  { checked: false, label: 'Congo - Kinshasa', value: 'CD' },
  { checked: false, label: 'Cook Islands', value: 'CK' },
  { checked: false, label: 'Costa Rica', value: 'CR' },
  { checked: false, label: 'Côte d’Ivoire', value: 'CI' },
  { checked: false, label: 'Croatia', value: 'HR' },
  { checked: false, label: 'Cuba', value: 'CU' },
  { checked: false, label: 'Curaçao', value: 'CW' },
  { checked: false, label: 'Cyprus', value: 'CY' },
  { checked: false, label: 'Czech Republic', value: 'CZ' },
  { checked: false, label: 'Denmark', value: 'DK' },
  { checked: false, label: 'Djibouti', value: 'DJ' },
  { checked: false, label: 'Dominica', value: 'DM' },
  { checked: false, label: 'Dominican Republic', value: 'DO' },
  { checked: false, label: 'Ecuador', value: 'EC' },
  { checked: false, label: 'Egypt', value: 'EG' },
  { checked: false, label: 'El Salvador', value: 'SV' },
  { checked: false, label: 'Equatorial Guinea', value: 'GQ' },
  { checked: false, label: 'Eritrea', value: 'ER' },
  { checked: false, label: 'Estonia', value: 'EE' },
  { checked: false, label: 'Eswatini', value: 'SZ' },
  { checked: false, label: 'Ethiopia', value: 'ET' },
  { checked: false, label: 'Falkland Islands', value: 'FK' },
  { checked: false, label: 'Faroe Islands', value: 'FO' },
  { checked: false, label: 'Fiji', value: 'FJ' },
  { checked: false, label: 'Finland', value: 'FI' },
  { checked: false, label: 'France', value: 'FR' },
  { checked: false, label: 'French Guiana', value: 'GF' },
  { checked: false, label: 'French Polynesia', value: 'PF' },
  { checked: false, label: 'French Southern Territories', value: 'TF' },
  { checked: false, label: 'Gabon', value: 'GA' },
  { checked: false, label: 'Gambia', value: 'GM' },
  { checked: false, label: 'Georgia', value: 'GE' },
  { checked: false, label: 'Germany', value: 'DE' },
  { checked: false, label: 'Ghana', value: 'GH' },
  { checked: false, label: 'Gibraltar', value: 'GI' },
  { checked: false, label: 'Greece', value: 'GR' },
  { checked: false, label: 'Greenland', value: 'GL' },
  { checked: false, label: 'Grenada', value: 'GD' },
  { checked: false, label: 'Guadeloupe', value: 'GP' },
  { checked: false, label: 'Guam', value: 'GU' },
  { checked: false, label: 'Guatemala', value: 'GT' },
  { checked: false, label: 'Guernsey', value: 'GG' },
  { checked: false, label: 'Guinea', value: 'GN' },
  { checked: false, label: 'Guinea-Bissau', value: 'GW' },
  { checked: false, label: 'Guyana', value: 'GY' },
  { checked: false, label: 'Haiti', value: 'HT' },
  { checked: false, label: 'Heard &amp; McDonald Islands', value: 'HM' },
  { checked: false, label: 'Honduras', value: 'HN' },
  { checked: false, label: 'Hong Kong SAR China', value: 'HK' },
  { checked: false, label: 'Hungary', value: 'HU' },
  { checked: false, label: 'Iceland', value: 'IS' },
  { checked: false, label: 'India', value: 'IN' },
  { checked: false, label: 'Indonesia', value: 'ID' },
  { checked: false, label: 'Iran', value: 'IR' },
  { checked: false, label: 'Iraq', value: 'IQ' },
  { checked: false, label: 'Ireland', value: 'IE' },
  { checked: false, label: 'Isle of Man', value: 'IM' },
  { checked: false, label: 'Israel', value: 'IL' },
  { checked: false, label: 'Italy', value: 'IT' },
  { checked: false, label: 'Jamaica', value: 'JM' },
  { checked: false, label: 'Japan', value: 'JP' },
  { checked: false, label: 'Jersey', value: 'JE' },
  { checked: false, label: 'Jordan', value: 'JO' },
  { checked: false, label: 'Kazakhstan', value: 'KZ' },
  { checked: false, label: 'Kenya', value: 'KE' },
  { checked: false, label: 'Kiribati', value: 'KI' },
  { checked: false, label: 'Kuwait', value: 'KW' },
  { checked: false, label: 'Kyrgyzstan', value: 'KG' },
  { checked: false, label: 'Laos', value: 'LA' },
  { checked: false, label: 'Latvia', value: 'LV' },
  { checked: false, label: 'Lebanon', value: 'LB' },
  { checked: false, label: 'Lesotho', value: 'LS' },
  { checked: false, label: 'Liberia', value: 'LR' },
  { checked: false, label: 'Libya', value: 'LY' },
  { checked: false, label: 'Liechtenstein', value: 'LI' },
  { checked: false, label: 'Lithuania', value: 'LT' },
  { checked: false, label: 'Luxembourg', value: 'LU' },
  { checked: false, label: 'Macao SAR China', value: 'MO' },
  { checked: false, label: 'Madagascar', value: 'MG' },
  { checked: false, label: 'Malawi', value: 'MW' },
  { checked: false, label: 'Malaysia', value: 'MY' },
  { checked: false, label: 'Maldives', value: 'MV' },
  { checked: false, label: 'Mali', value: 'ML' },
  { checked: false, label: 'Malta', value: 'MT' },
  { checked: false, label: 'Marshall Islands', value: 'MH' },
  { checked: false, label: 'Martinique', value: 'MQ' },
  { checked: false, label: 'Mauritania', value: 'MR' },
  { checked: false, label: 'Mauritius', value: 'MU' },
  { checked: false, label: 'Mayotte', value: 'YT' },
  { checked: false, label: 'Mexico', value: 'MX' },
  { checked: false, label: 'Micronesia', value: 'FM' },
  { checked: false, label: 'Moldova', value: 'MD' },
  { checked: false, label: 'Monaco', value: 'MC' },
  { checked: false, label: 'Mongolia', value: 'MN' },
  { checked: false, label: 'Montenegro', value: 'ME' },
  { checked: false, label: 'Montserrat', value: 'MS' },
  { checked: false, label: 'Morocco', value: 'MA' },
  { checked: false, label: 'Mozambique', value: 'MZ' },
  { checked: false, label: 'Myanmar (Burma)', value: 'MM' },
  { checked: false, label: 'Namibia', value: 'NA' },
  { checked: false, label: 'Nauru', value: 'NR' },
  { checked: false, label: 'Nepal', value: 'NP' },
  { checked: false, label: 'Netherlands', value: 'NL' },
  { checked: false, label: 'New Caledonia', value: 'NC' },
  { checked: false, label: 'New Zealand', value: 'NZ' },
  { checked: false, label: 'Nicaragua', value: 'NI' },
  { checked: false, label: 'Niger', value: 'NE' },
  { checked: false, label: 'Nigeria', value: 'NG' },
  { checked: false, label: 'Niue', value: 'NU' },
  { checked: false, label: 'Norfolk Island', value: 'NF' },
  { checked: false, label: 'North Korea', value: 'KP' },
  { checked: false, label: 'North Macedonia', value: 'MK' },
  { checked: false, label: 'Northern Mariana Islands', value: 'MP' },
  { checked: false, label: 'Norway', value: 'NO' },
  { checked: false, label: 'Oman', value: 'OM' },
  { checked: false, label: 'Pakistan', value: 'PK' },
  { checked: false, label: 'Palau', value: 'PW' },
  { checked: false, label: 'Palestinian Territories', value: 'PS' },
  { checked: false, label: 'Panama', value: 'PA' },
  { checked: false, label: 'Papua New Guinea', value: 'PG' },
  { checked: false, label: 'Paraguay', value: 'PY' },
  { checked: false, label: 'Peru', value: 'PE' },
  { checked: false, label: 'Philippines', value: 'PH' },
  { checked: false, label: 'Pitcairn Islands', value: 'PN' },
  { checked: false, label: 'Poland', value: 'PL' },
  { checked: false, label: 'Portugal', value: 'PT' },
  { checked: false, label: 'Puerto Rico', value: 'PR' },
  { checked: false, label: 'Qatar', value: 'QA' },
  { checked: false, label: 'Réunion', value: 'RE' },
  { checked: false, label: 'Romania', value: 'RO' },
  { checked: false, label: 'Russia', value: 'RU' },
  { checked: false, label: 'Rwanda', value: 'RW' },
  { checked: false, label: 'Samoa', value: 'WS' },
  { checked: false, label: 'San Marino', value: 'SM' },
  { checked: false, label: 'São Tomé &amp; Príncipe', value: 'ST' },
  { checked: false, label: 'Saudi Arabia', value: 'SA' },
  { checked: false, label: 'Senegal', value: 'SN' },
  { checked: false, label: 'Serbia', value: 'RS' },
  { checked: false, label: 'Seychelles', value: 'SC' },
  { checked: false, label: 'Sierra Leone', value: 'SL' },
  { checked: false, label: 'Singapore', value: 'SG' },
  { checked: false, label: 'Sint Maarten', value: 'SX' },
  { checked: false, label: 'Slovakia', value: 'SK' },
  { checked: false, label: 'Slovenia', value: 'SI' },
  { checked: false, label: 'Solomon Islands', value: 'SB' },
  { checked: false, label: 'Somalia', value: 'SO' },
  { checked: false, label: 'South Africa', value: 'ZA' },
  { checked: false, label: 'South Korea', value: 'KR' },
  { checked: false, label: 'South Sudan', value: 'SS' },
  { checked: false, label: 'Spain', value: 'ES' },
  { checked: false, label: 'Sri Lanka', value: 'LK' },
  { checked: false, label: 'St. Barthélemy', value: 'BL' },
  { checked: false, label: 'St. Helena', value: 'SH' },
  { checked: false, label: 'St. Kitts &amp; Nevis', value: 'KN' },
  { checked: false, label: 'St. Lucia', value: 'LC' },
  { checked: false, label: 'St. Martin', value: 'MF' },
  { checked: false, label: 'St. Pierre &amp; Miquelon', value: 'PM' },
  { checked: false, label: 'St. Vincent &amp; Grenadines', value: 'VC' },
  { checked: false, label: 'Sudan', value: 'SD' },
  { checked: false, label: 'Suriname', value: 'SR' },
  { checked: false, label: 'Svalbard &amp; Jan Mayen', value: 'SJ' },
  { checked: false, label: 'Sweden', value: 'SE' },
  { checked: false, label: 'Switzerland', value: 'CH' },
  { checked: false, label: 'Syria', value: 'SY' },
  { checked: false, label: 'Taiwan', value: 'TW' },
  { checked: false, label: 'Tajikistan', value: 'TJ' },
  { checked: false, label: 'Tanzania', value: 'TZ' },
  { checked: false, label: 'Thailand', value: 'TH' },
  { checked: false, label: 'Timor-Leste', value: 'TL' },
  { checked: false, label: 'Togo', value: 'TG' },
  { checked: false, label: 'Tokelau', value: 'TK' },
  { checked: false, label: 'Tonga', value: 'TO' },
  { checked: false, label: 'Trinidad &amp; Tobago', value: 'TT' },
  { checked: false, label: 'Tunisia', value: 'TN' },
  { checked: false, label: 'Türkiye', value: 'TR' },
  { checked: false, label: 'Turkmenistan', value: 'TM' },
  { checked: false, label: 'Turks &amp; Caicos Islands', value: 'TC' },
  { checked: false, label: 'Tuvalu', value: 'TV' },
  { checked: false, label: 'U.S. Outlying Islands', value: 'UM' },
  { checked: false, label: 'U.S. Virgin Islands', value: 'VI' },
  { checked: false, label: 'Uganda', value: 'UG' },
  { checked: false, label: 'Ukraine', value: 'UA' },
  { checked: false, label: 'United Arab Emirates', value: 'AE' },
  { checked: false, label: 'United Kingdom', value: 'GB' },
  { checked: false, label: 'United States', value: 'US' },
  { checked: false, label: 'Uruguay', value: 'UY' },
  { checked: false, label: 'Uzbekistan', value: 'UZ' },
  { checked: false, label: 'Vanuatu', value: 'VU' },
  { checked: false, label: 'Vatican City', value: 'VA' },
  { checked: false, label: 'Venezuela', value: 'VE' },
  { checked: false, label: 'Vietnam', value: 'VN' },
  { checked: false, label: 'Wallis &amp; Futuna', value: 'WF' },
  { checked: false, label: 'Western Sahara', value: 'EH' },
  { checked: false, label: 'Yemen', value: 'YE' },
  { checked: false, label: 'Zambia', value: 'ZM' },
  { checked: false, label: 'Zimbabwe', value: 'ZW' },
  { checked: false, label: '(Blank)', value: '(Blank)' },
  { checked: false, label: '(Not Blank)', value: '(Not Blank)' },
];
